[package]
name = "simulation_lib"
version = "0.1.0"
edition = "2024"

[features]
default = ["logging", "parallel"]

# Features
logging = ["dep:tracing"]
parallel = ["dep:rayon"]
cfl_time_step = []



# [dev-dependencies]
# criterion ={ version = "0.5.1", features = ["html_reports"] }

# [[bench]]
# name = "bench_System1D_inc_time"
# harness = false

# for profiling with flamegraph
# [profile.release]
# debug = true

[dependencies]
# linear algebra
nalgebra = "0.35"

# collision detection
parry3d-f64 = "0.28"

# surface reconstruction
splashsurf_lib = "0.14.1"

# numer handling
num-traits = "0.2.19"

# gauss (legendre) quadrature
gauss-quad = "0.3.1"

# Faster hash map for uniform grid
rustc-hash = "2.1.1"

# for communication between threads
crossbeam = "0.8.4"

# parsing file content
serde = { version = "1.0", features = ["derive"] }

# loading .obj and .mtl files (triangle meshes)
tobj = "4.0.4"

# storing struct in the RON format
ron = "0.11"

# storing measurement data
csv = "1.4"

# loading .toml files
toml = "0.9"

# writing to binary files
bincode = "2.0.1"

bytemuck = { version = "1.24.0", features = [ "derive" ] }

## Error handling
thiserror = "2.0.19"

# optional
## logging
tracing = { version = "0.1.41", optional = true }

## multithreading of for loops
rayon = { version = "1.11", optional = true }
