# Configuration file
[procedures]
kernel_function = "CubicBSpline3D" # CubicBSpline3D
integration_scheme = "EulerCromer" #
pressure_solver = "IISPH" #
neighbor_search = "SpatialHashing" # SpatialHashing, Octree
boundary_handling = "VolumeMapBoundary" # StaticSampleBoundary, VolumeMapBoundary

[parameters] # General parameters
buffer_length_limit = 1000
rest_density_grid_spacing = 0.8 # (not hot swappable)
kernel_support_radius = 1.6 # (not hot swappable)
disable_particles_below = -50
fluid_viscosity = 0.2
boundary_viscosity = 0.2
# boundary_pressure_acceleration_weighting = 0.7 # gamma
boundary_pressure_acceleration_weighting = 1.0 # gamma
boundary_rest_volume_weighting = 1.0 # gamma

# local pressure
stiffness = 15000000.0 # k
# global pressure
# solver_iterations = 5 # deprecated
target_density_error = 0.05 # in percent
relaxation_factor = 0.5 # omega
min_diagonal_element = 1e-10 # epsilon

# constant time step
time_increment = 0.006
# cfl time step
# max_time_increment = 0.01
# cfl_number = 0.4

[[parameters.fluid]]
id = 0
rest_density = 900.0 # rest density of fluid

[[parameters.fluid]]
id = 1
rest_density = 100.0 # rest density of fluid
