# Scene file
[light]
position = [ 2.0, 2.0, 100.0 ]

[meshes]
cube_out = "/mnt/Code/fluid-simulation/cube_face_normals_outwards.obj"
cube_in = "/mnt/Code/fluid-simulation/cube_face_normals_inwards.obj"
sphere_out = "/mnt/Code/fluid-simulation/sphere_face_normals_outwards.obj"
sphere_in = "/mnt/Code/fluid-simulation/sphere_face_normals_inwards.obj"

# TINY TEST CUBE
[[fluid]]
mesh = "cube_out"
fluid_id = 0
translation = [0.0, 0.0, 0.0]
rotation_euler_deg = [0.0, 0.0, 0.0]
scale = 1.0

[[boundary.static]]
mesh = "cube_in"
boundary_id = 0
translation = [0.0, 0.0, 0.0]
scale = 7.0
