[package]
name = "rusty_fluid_solver"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion ={ version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "bench_System1D_inc_time"
harness = false

[dependencies]
nalgebra = "0.33.2"
num-traits = "0.2.19"
cgmath = "0.18"

tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-appender = "0.2.3"

clap = {version = "4.5.23", features = ["derive"] }

# iced = "0.13.1"
# iced_wgpu = "0.13.5"
iced_widget = { git = "https://github.com/iced-rs/iced", rev = "7a97773f1796fa7889435c78305d287449dd05a4",  package = "iced_widget", features = ["wgpu"]}
iced_wgpu = { git = "https://github.com/iced-rs/iced", rev = "7a97773f1796fa7889435c78305d287449dd05a4", package = "iced_wgpu" }
iced_winit = { git = "https://github.com/iced-rs/iced", rev = "7a97773f1796fa7889435c78305d287449dd05a4", package = "iced_winit" }
# wgpu = "25.0.0"
# winit = "0.30.10"

tobj = { version = "4.0.2", default-features = false, features = ["async"]}

bytemuck = { version = "1.20.0", features = [ "derive" ] }

pollster = "0.4.0"

anyhow = "1.0.93"
fs_extra = "1.3"
glob = "0.3.1"

serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
