# Scene configuration file

[params]
buffer_length_limit = 3
time_inc = 0.005
viscosity = 1.8
stiffness = 10.0
integration_scheme = "EulerCromer" # Not implemented yet
# Options: ExplicitEuler, ImplicitEuler, EulerCromer, Verlet,
particle_mass = 0.001
particle_diameter = 0.8 # (does not update visualization yet)

[scene.particles]
n_particles_x = 1
n_particles_y = 1
n_particles_z = 1
x_offset = 0.0
y_offset = 0.8
z_offset = 5.0
particle_spacing = 1.6

[scene.boundary_particles]
n_floor_particles_x = 5
n_floor_particles_y = 3
n_floor_particles_z = 2
wall_height = 1 # wall is at the edge but above floor
x_wall_thickness = 1
y_wall_thickness = 0
x_offset = -1.6
y_offset = 0.0
z_offset = 0.0
particle_spacing = 0.8

[springs]

[scene.light]
position = [ 2.0, 10.0, 2.0 ] # (not updatable yet)