[package]
name = "meta"
version = "0.1.0"
edition = "2024"

[dependencies]
simulation_lib = { path = "../simulation_lib", default-features = false }
rendering_lib = { path = "../rendering_lib", default-features = false }

[features]
# default = ["logging", "pseudo_volume_boundary"]
default = ["logging", "parallel", "pseudo_volume_boundary"]
# default = ["logging", "parallel", "pseudo_volume_boundary", "cfl_time_step"]

logging = ["simulation_lib/logging", "rendering_lib/logging"]
parallel = ["simulation_lib/parallel"]
springs = ["simulation_lib/springs"] # does not work yet
pseudo_volume_boundary = ["simulation_lib/pseudo_volume_boundary"]
cfl_time_step = ["simulation_lib/cfl_time_step"]
