[package]
name = "meta"
version = "0.1.0"
edition = "2024"

[dependencies]
simulation_lib = { path = "../simulation_lib", default-features = false }
rendering_lib = { path = "../rendering_lib", default-features = false }

[features]
# Default-Features: werden automatisch aktiv, wenn nichts anderes angegeben ist
default = ["logging", "parallelized_sph", "global_pressure"]

logging = ["simulation_lib/logging", "rendering_lib/logging"]
parallelized_sph = ["simulation_lib/parallelized_sph"]
implicit_euler = ["simulation_lib/implicit_euler"]
springs = ["simulation_lib/springs"]
pseudo_mass_boundary = ["simulation_lib/pseudo_mass_boundary"]
local_pressure = ["simulation_lib/local_pressure"]
splitting = ["simulation_lib/splitting"]
global_pressure = ["simulation_lib/global_pressure"]
