[package]
name = "meta"
version = "0.1.0"
edition = "2024"

[dependencies]
simulation_lib = { path = "../simulation_lib", default-features = false }
rendering_lib = { path = "../rendering_lib", default-features = false }

[features]
# Default-Features: werden automatisch aktiv, wenn nichts anderes angegeben ist
# default = ["logging", "local_pressure", "pseudo_volume_boundary"]
# default = ["logging", "parallelized_sph", "local_pressure", "pseudo_volume_boundary"]
# default = ["logging", "parallelized_sph", "local_pressure", "optimized_source_term", "pseudo_volume_boundary"]
# default = ["logging", "global_pressure", "pseudo_volume_boundary"]
# default = ["logging", "global_pressure", "optimized_source_term", "pseudo_volume_boundary"]
default = ["logging", "parallelized_sph", "global_pressure", "pseudo_volume_boundary"]
# default = ["logging", "parallelized_sph", "global_pressure", "optimized_source_term", "pseudo_volume_boundary"]
#, "cfl_time_step"] # "parallelized_sph",

logging = ["simulation_lib/logging", "rendering_lib/logging"]
parallelized_sph = ["simulation_lib/parallelized_sph"]
implicit_euler = ["simulation_lib/implicit_euler"]
springs = ["simulation_lib/springs"]
pseudo_volume_boundary = ["simulation_lib/pseudo_volume_boundary"]
local_pressure = ["simulation_lib/local_pressure"]
splitting = ["simulation_lib/splitting"]
global_pressure = ["simulation_lib/global_pressure"]
optimized_source_term = ["simulation_lib/optimized_source_term"]
cfl_time_step = ["simulation_lib/cfl_time_step"]
