[package]
name = "rusty_player"
version = "0.1.0"
edition = "2024"

# [dev-dependencies]
# criterion ={ version = "0.5.1", features = ["html_reports"] }

# [[bench]]
# name = "bench_System1D_inc_time"
# harness = false

# for profiling with flamegraph
# [profile.release]
# debug = true

[dependencies]
simulation_lib = { path = "../simulation_lib" }
rendering_lib = { path = "../rendering_lib" }

# linear algebra
nalgebra = "0.34.1"
cgmath = "0.18"

# numer handling
num-traits = "0.2.19"

# Faster hash map for uniform grid
rustc-hash = "2.1.1"

# command line parser
clap = {version = "4.5.51", features = ["derive"] }

# for communication between threads
crossbeam = "0.8.4"

# parsing file content
serde = { version = "1.0", features = ["derive"] }

# storing struct in the RON format
ron = "0.11"

# storing measurement data
csv = "1.4"

# loading .toml files
toml = "0.9"

# writing to binary files
bincode = "2.0.1"

# saving rendered image to image file
image = "0.25.9"

# error handling
anyhow = "1.0.100"

# visualization
iced_widget = { git = "https://github.com/iced-rs/iced", rev = "7a97773f1796fa7889435c78305d287449dd05a4",  package = "iced_widget", features = ["wgpu"]}
iced_wgpu = { git = "https://github.com/iced-rs/iced", rev = "7a97773f1796fa7889435c78305d287449dd05a4", package = "iced_wgpu" }
iced_winit = { git = "https://github.com/iced-rs/iced", rev = "7a97773f1796fa7889435c78305d287449dd05a4", package = "iced_winit" }

# load sphere for visualization
tobj = { version = "4.0.3", default-features = false, features = ["async"]}

bytemuck = { version = "1.24.0", features = [ "derive" ] }

pollster = "0.4.0"

# logging
tracing = { version = "0.1.41"}
tracing-subscriber = { version = "0.3.20"}
