[package]
name = "sci-phi-player-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
# simulation library
simulation_lib = { path = "../simulation_lib", features = ["default"]}

rendering_lib = { path = "../rendering_lib", features = ["default"]}

# for communication between threads
crossbeam = "0.8.4"

# saving rendered image to image file
image = "0.25.9"

# storing struct in the RON format
ron = "0.12"

# error handling
anyhow = "1.0.100"

# logging
tracing = { version = "0.1.41"}
tracing-subscriber = { version = "0.3.20"}
