//! Sampling utilities

use nalgebra::{Point3, Vector2};
use parry3d_f64::math::Vec3;
use parry3d_f64::query::PointQuery;
use parry3d_f64::shape::TriMesh;

pub fn sample_volume_shifted(mesh: &TriMesh, spacing: f64) -> Vec<Point3<f64>> {
    let aabb = mesh.local_aabb();
    let mut points: Vec<nalgebra::OPoint<f64, nalgebra::Const<3>>> = Vec::new();

    let half_spacing = spacing / 2.0;

    let mut x = aabb.mins.x + half_spacing;
    while x <= aabb.maxs.x {
        let mut y = aabb.mins.y + half_spacing;
        while y <= aabb.maxs.y {
            let mut z = aabb.mins.z + half_spacing;
            let mut layer: usize = 0;
            while z <= aabb.maxs.z {
                let shift = if layer % 2 == 1 { half_spacing } else { 0.0 };
                if mesh.contains_local_point(Vec3::new(x + shift, y, z)) {
                    points.push(Point3::new(x + shift, y, z));
                }
                z += spacing;
                layer += 1;
            }
            y += spacing;
        }
        x += spacing;
    }
    points
}

/// Samples the interior of a triangle with an approximately uniform, isotropic grid
/// of points.
///
/// Unlike a naive affine parametrization over `edge1`/`edge2`, this constructs an
/// orthonormal basis (`e_u`, `e_v`) in the triangle's plane via Gram-Schmidt
/// orthogonalization and rasters a regular Euclidean grid with spacing `spacing` in
/// that basis. This keeps the sample density constant and isotropic regardless of the
/// triangle's edge lengths or the angle between them, which is important for triangles
/// distorted by anisotropic mesh scaling.
///
/// Points are generated by iterating over the bounding box of the triangle in the
/// `(x, y)` coordinates of the orthonormal basis and keeping only those that fall
/// inside the triangle (checked via [`point_in_triangle`]).
///
/// Samples along a shared edge of two adjacent triangles are **not** guaranteed to be
/// consistent between triangles, since each triangle is rasterized independently; small
/// gaps or duplicate points near edges can occur.
///
/// # Arguments
///
/// * `v0`, `v1`, `v2` - The three vertices of the triangle.
/// * `spacing` - Target distance between neighboring sample points.
///
/// # Returns
///
/// A vector of sample points lying inside (or on the boundary of) the triangle,
/// including the origin vertex `v0`. Returns an empty vector for degenerate triangles
/// (zero area, or `v0 == v1`).
fn sample_triangle_surface(
    v0: &Point3<f64>,
    v1: &Point3<f64>,
    v2: &Point3<f64>,
    spacing: f64,
) -> Vec<Point3<f64>> {
    let edge1 = v1 - v0;
    let edge2 = v2 - v0;

    let len1 = edge1.norm();
    if len1 < 1e-12 {
        return Vec::new();
    }

    // Orthonormale Basis in der Dreiecksebene (Gram-Schmidt).
    let e_u = edge1 / len1;
    let proj = edge2.dot(&e_u);
    let perp = edge2 - e_u * proj;
    let perp_len = perp.norm();
    if perp_len < 1e-12 {
        return Vec::new(); // entartetes Dreieck
    }
    let e_v = perp / perp_len;

    // 2D-Koordinaten der Eckpunkte in dieser Basis.
    let p0: Vector2<f64> = Vector2::new(0.0, 0.0);
    let p1: Vector2<f64> = Vector2::new(len1, 0.0);
    let p2: Vector2<f64> = Vector2::new(proj, perp_len);

    let min_x = p0.x.min(p1.x).min(p2.x);
    let max_x = p0.x.max(p1.x).max(p2.x);
    let min_y = p0.y.min(p1.y).min(p2.y);
    let max_y = p0.y.max(p1.y).max(p2.y);

    let nx = ((max_x - min_x) / spacing).ceil() as usize;
    let ny = ((max_y - min_y) / spacing).ceil() as usize;

    let mut points = Vec::new();
    for j in 0..=ny {
        let y = min_y + j as f64 * spacing;
        for i in 0..=nx {
            let x = min_x + i as f64 * spacing;
            if point_in_triangle(Vector2::new(x, y), p0, p1, p2) {
                points.push(v0 + e_u * x + e_v * y);
            }
        }
    }
    points
}

/// Tests whether a 2D point lies inside (or on the boundary of) a triangle.
///
/// Uses the sign of the [`cross2`] cross product along each edge of the triangle: the
/// point is inside if it is on the same side (or exactly on the boundary) of all three
/// edges.
///
/// # Arguments
///
/// * `p` - The point to test.
/// * `a`, `b`, `c` - The vertices of a non-degenerate triangle, in either winding order.
///
/// # Returns
///
/// `true` if `p` lies inside or on the boundary of the triangle `a`-`b`-`c`.
fn point_in_triangle(p: Vector2<f64>, a: Vector2<f64>, b: Vector2<f64>, c: Vector2<f64>) -> bool {
    let d1 = cross2(b - a, p - a);
    let d2 = cross2(c - b, p - b);
    let d3 = cross2(a - c, p - c);
    let has_neg = d1 < 0.0 || d2 < 0.0 || d3 < 0.0;
    let has_pos = d1 > 0.0 || d2 > 0.0 || d3 > 0.0;
    !(has_neg && has_pos)
}

/// Computes the 2D cross product (the scalar z-component of the 3D cross product) of
/// two vectors.
///
/// Positive when `b` lies counter-clockwise from `a`, negative when clockwise, and
/// zero when `a` and `b` are collinear.
///
/// # Arguments
///
/// * `a`, `b` - The two vectors.
///
/// # Returns
///
/// The scalar cross product `a.x * b.y - a.y * b.x`.
fn cross2(a: Vector2<f64>, b: Vector2<f64>) -> f64 {
    a.x * b.y - a.y * b.x
}

/// Samples the surface of a triangle mesh with an approximately uniform, isotropic
/// grid of points.
///
/// Each triangle of `mesh` is sampled independently via [`sample_triangle_surface`]
/// with the given `spacing`; the resulting per-triangle point sets are concatenated.
/// Because sampling is done per-triangle, points near shared edges of adjacent
/// triangles are not guaranteed to align.
///
/// # Arguments
///
/// * `mesh` - The triangle mesh whose surface is sampled.
/// * `spacing` - Target distance between neighboring sample points.
///
/// # Returns
///
/// A vector of sample points covering the surface of `mesh`.
pub fn sample_triangle_mesh_surface(mesh: &TriMesh, spacing: f64) -> Vec<Point3<f64>> {
    mesh.triangles()
        .flat_map(|tri| {
            let a = Point3::new(tri.a.x, tri.a.y, tri.a.z);
            let b = Point3::new(tri.b.x, tri.b.y, tri.b.z);
            let c = Point3::new(tri.c.x, tri.c.y, tri.c.z);
            sample_triangle_surface(&a, &b, &c, spacing)
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    // ─── cross2 ───────────────────────────────────────────────────────

    #[test]
    fn cross2_of_orthogonal_unit_vectors_is_one() {
        let a = Vector2::new(1.0, 0.0);
        let b = Vector2::new(0.0, 1.0);
        assert_eq!(cross2(a, b), 1.0);
    }

    #[test]
    fn cross2_is_antisymmetric() {
        let a = Vector2::new(2.0, 3.0);
        let b = Vector2::new(-1.0, 4.0);
        assert_eq!(cross2(a, b), -cross2(b, a));
    }

    #[test]
    fn cross2_of_collinear_vectors_is_zero() {
        let a = Vector2::new(2.0, 4.0);
        let b = Vector2::new(1.0, 2.0); // scalar multiple of a
        assert!(cross2(a, b).abs() < 1e-12);
    }

    #[test]
    fn cross2_with_zero_vector_is_zero() {
        let a = Vector2::new(3.0, -5.0);
        assert_eq!(cross2(a, Vector2::new(0.0, 0.0)), 0.0);
    }

    // ─── point_in_triangle ────────────────────────────────────────────

    fn unit_right_triangle() -> (Vector2<f64>, Vector2<f64>, Vector2<f64>) {
        (
            Vector2::new(0.0, 0.0),
            Vector2::new(1.0, 0.0),
            Vector2::new(0.0, 1.0),
        )
    }

    #[test]
    fn point_in_triangle_true_for_centroid() {
        let (a, b, c) = unit_right_triangle();
        assert!(point_in_triangle((a + b + c) / 3.0, a, b, c));
    }

    #[test]
    fn point_in_triangle_false_for_point_outside() {
        let (a, b, c) = unit_right_triangle();
        assert!(!point_in_triangle(Vector2::new(2.0, 2.0), a, b, c));
    }

    #[test]
    fn point_in_triangle_true_on_vertices() {
        let (a, b, c) = unit_right_triangle();
        assert!(point_in_triangle(a, a, b, c));
        assert!(point_in_triangle(b, a, b, c));
        assert!(point_in_triangle(c, a, b, c));
    }

    #[test]
    fn point_in_triangle_true_on_edge_midpoint() {
        let (a, b, c) = unit_right_triangle();
        assert!(point_in_triangle((a + b) / 2.0, a, b, c));
    }

    #[test]
    fn point_in_triangle_is_winding_order_independent() {
        let (a, b, c) = unit_right_triangle();
        let inside = Vector2::new(0.2, 0.2);
        let outside = Vector2::new(0.9, 0.9);
        assert_eq!(
            point_in_triangle(inside, a, b, c),
            point_in_triangle(inside, a, c, b)
        );
        assert_eq!(
            point_in_triangle(outside, a, b, c),
            point_in_triangle(outside, a, c, b)
        );
        assert!(point_in_triangle(inside, a, b, c));
        assert!(!point_in_triangle(outside, a, b, c));
    }

    // ─── sample_triangle_surface ──────────────────────────────────────

    #[test]
    fn sample_triangle_surface_zero_length_edge_returns_empty() {
        let v0 = Point3::new(0.0, 0.0, 0.0);
        let v1 = Point3::new(0.0, 0.0, 0.0); // v0 == v1
        let v2 = Point3::new(0.0, 1.0, 0.0);
        assert!(sample_triangle_surface(&v0, &v1, &v2, 0.1).is_empty());
    }

    #[test]
    fn sample_triangle_surface_collinear_points_returns_empty() {
        let v0 = Point3::new(0.0, 0.0, 0.0);
        let v1 = Point3::new(1.0, 0.0, 0.0);
        let v2 = Point3::new(2.0, 0.0, 0.0); // collinear -> zero area
        assert!(sample_triangle_surface(&v0, &v1, &v2, 0.1).is_empty());
    }

    #[test]
    fn sample_triangle_surface_right_triangle_matches_expected_grid() {
        // v0=(0,0,0), v1=(1,0,0), v2=(0,1,0) is exactly aligned with the
        // orthonormal basis constructed internally (proj == 0), so the
        // resulting grid is fully predictable by hand for spacing = 0.5.
        let v0 = Point3::new(0.0, 0.0, 0.0);
        let v1 = Point3::new(1.0, 0.0, 0.0);
        let v2 = Point3::new(0.0, 1.0, 0.0);
        let points = sample_triangle_surface(&v0, &v1, &v2, 0.5);

        let expected = [
            Point3::new(0.0, 0.0, 0.0),
            Point3::new(0.5, 0.0, 0.0),
            Point3::new(1.0, 0.0, 0.0),
            Point3::new(0.0, 0.5, 0.0),
            Point3::new(0.5, 0.5, 0.0),
            Point3::new(0.0, 1.0, 0.0),
        ];

        assert_eq!(points.len(), expected.len());
        for e in &expected {
            assert!(
                points.iter().any(|p| (p - e).norm() < 1e-9),
                "expected point {e:?} not found in {points:?}"
            );
        }
    }

    #[test]
    fn sample_triangle_surface_includes_origin_vertex() {
        let v0 = Point3::new(0.0, 0.0, 0.0);
        let v1 = Point3::new(1.0, 0.0, 0.0);
        let v2 = Point3::new(0.0, 1.0, 0.0);
        let points = sample_triangle_surface(&v0, &v1, &v2, 0.5);
        assert!(points.iter().any(|p| (p - v0).norm() < 1e-9));
    }

    #[test]
    fn sample_triangle_surface_all_points_lie_in_triangle_plane() {
        // Non-axis-aligned, obtuse-at-v0 triangle (negative projection) to
        // exercise the Gram-Schmidt basis construction with proj < 0.
        let v0 = Point3::new(1.0, 1.0, 1.0);
        let v1 = Point3::new(3.0, 1.0, 2.0);
        let v2 = Point3::new(-2.0, 3.0, 0.5);
        let normal = (v1 - v0).cross(&(v2 - v0)).normalize();

        let points = sample_triangle_surface(&v0, &v1, &v2, 0.3);
        assert!(!points.is_empty());
        for p in &points {
            let d = (p - v0).dot(&normal);
            assert!(d.abs() < 1e-9, "point {p:?} deviates from plane by {d}");
        }
    }

    #[test]
    fn sample_triangle_surface_finer_spacing_yields_more_points() {
        let v0 = Point3::new(0.0, 0.0, 0.0);
        let v1 = Point3::new(2.0, 0.0, 0.0);
        let v2 = Point3::new(0.0, 2.0, 0.0);
        let coarse = sample_triangle_surface(&v0, &v1, &v2, 1.0);
        let fine = sample_triangle_surface(&v0, &v1, &v2, 0.25);
        assert!(fine.len() > coarse.len());
    }

    // ─── sample_triangle_mesh_surface: aggregation (needs the private
    // helper for a ground-truth comparison, so it must live here) ──────

    #[test]
    fn sample_triangle_mesh_surface_of_single_triangle_matches_direct_call() {
        let positions = vec![
            Vec3::new(0.0, 0.0, 0.0),
            Vec3::new(1.0, 0.0, 0.0),
            Vec3::new(0.0, 1.0, 0.0),
        ];
        let indices = vec![[0u32, 1, 2]];
        let mesh = TriMesh::new(positions, indices).unwrap();

        let spacing = 0.4;
        let via_mesh = sample_triangle_mesh_surface(&mesh, spacing);
        let direct = sample_triangle_surface(
            &Point3::new(0.0, 0.0, 0.0),
            &Point3::new(1.0, 0.0, 0.0),
            &Point3::new(0.0, 1.0, 0.0),
            spacing,
        );

        assert_eq!(via_mesh.len(), direct.len());
    }
}
