# Scene file
[light]
position = [ 2.0, 2.0, 100.0 ]

[meshes]
cube = "/mnt/Code/fluid-simulation/rusty_fluid_solver/cube.obj"
sphere = "/mnt/Code/fluid-simulation/rusty_fluid_solver/sphere.obj"

[[fluid]]
mesh = "cube"
fluid_id = 0
position = [15.0, 20.0, 10.0]
rotation_euler_deg = [0.0, 0.0, 0.0]
scale = 15.0

[[fluid]]
mesh = "cube"
fluid_id = 1
position = [-5.0, 20.0, 10.0]
scale = 15.0

[[boundary.static]]
mesh = "sphere"
boundary_id = 0
position = [10.0, 0.0, 10.0]
scale = 30.0

# [[boundary.dynamic]]
# mesh = "cube"
# boundary_id = 1
# position = [2.0, 0.0, 0.0]
# rotation_euler_deg = [0.0, 0.0, 0.0]
