# Scene configuration file

[parameters]
buffer_length_limit = 3000 # 3000
rest_density = 900.0 # rest density of fluid
rest_density_grid_spacing = 0.8 # (not hot swappable)
smoothing_length = 0.8 # (not hot swappable)
kernel_support_radius = 1.6 # (not hot swappable)
disable_particles_below = -30
fluid_viscosity = 0.2
boundary_viscosity = 0.2
boundary_pressure_acceleration_weighting = 0.7 # gamma
boundary_rest_volume_weighting = 1.0 # gamma

# local pressure
stiffness = 15000000.0 # k
# global pressure
# solver_iterations = 5 # deprecated
target_density_error = 0.1 # in percent
relaxation_factor = 0.5 # omega
min_diagonal_element = 1e-25 # epsilon

# constant time step
time_increment = 0.01
# cfl time step
max_time_increment = 0.02

[light]
position = [ 20.0, 100.0, 60.0 ] # (not hot swappable)

[scene]
type = "Spiral"

[scene.parameters]
base = [0.0, 0.0, 0.0]

[scene.parameters.fluid_particles]
number_of_particles = 19000

[scene.parameters.boundary]
length = 50
width = 50
minimum_heigth = 50
inner_width1 = 15
inner_length1 = 35
inner_length2 = 20
whole_height = 7
inner_length3 = 10
barrier_height = 5
