# Scene configuration file

[parameters]
buffer_length_limit = 1
rest_density = 900.0 # rest density of fluid
rest_density_grid_spacing = 0.8 # (not hot swappable)
kernel_support_radius = 1.6 # (not hot swappable)
disable_particles_below = -20
fluid_viscosity = 0.2
boundary_viscosity = 0.2
boundary_pressure_acceleration_weighting = 0.7 # gamma
boundary_rest_volume_weighting = 1.0 # gamma

# local pressure
stiffness = 15000000.0 # k
# global pressure
# solver_iterations = 5 # deprecated
target_density_error = 0.1 # in percent
relaxation_factor = 0.5 # omega
min_diagonal_element = 1e-25 # epsilon

# constant time step
time_increment = 0.005
# cfl time step
max_time_increment = 0.02

[light]
position = [ 2.0, 10.0, 2.0 ] # (not hot swappable)

[scene]
type = "NoLidCube"

[scene.parameters.particles]
n_particles_x = 3
n_particles_y = 2
n_particles_z = 3
x_offset = 0.0
y_offset = 0.425
z_offset = 1.5
particle_spacing = 0.85

[scene.parameters.boundary_particles]
n_floor_particles_x = 7
n_floor_particles_y = 5
n_floor_particles_z = 2
wall_height = 6 # wall is at the edge but above floor
x_wall_thickness = 1
y_wall_thickness = 1
x_offset = -1.7
y_offset = -0.85
z_offset = -10.0
particle_spacing = 0.8
